### PR TITLE
1.0.5 - 04/11/2021

### PR DESCRIPTION
**Pull request by zikeji**
data extracted using your extractor repo against the 1.0.5 patch files

### CODE REVIEW

**Comment by Kattoor** [comment]
I totally forgot to push the update, thanks @zikeji!

**Comment by hydrobromic** [comment]
if we can get data from 1.0.6 I will love you :) @Kattoor @zikeji

**Comment by zikeji** [comment]
> if we can get data from 1.0.6 I will love you :) @Kattoor @zikeji

1.0.5 jumped directly to 1.1.0

https://github.com/zikeji/nw-datasheets-json

**Comment by hydrobromic** [comment]
> > if we can get data from 1.0.6 I will love you :) @Kattoor @zikeji
> 
> 1.0.5 jumped directly to 1.1.0
> 
> https://github.com/zikeji/nw-datasheets-json

Thank you very much!!!

**Pull request merged**
